//This class tests the HTTP Client and therefore the method in the login controller
//Please be aware since the DB is constantly changing the service and provider Id  might not work and
// therefore cause failing tests
###
GET http://localhost:3000/search
Content-Type: application/json

> {%
client.test("get all Services", function() {
  client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
GET http://localhost:3000/search/filter/:textsearch?category=Gastronomy&city=Bern
Content-Type: application/json

> {%
client.test("get filtered gastronomy and city services", function() {
  client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
GET http://localhost:3000/search/filter/:textsearch?city=Bern
Content-Type: application/json

> {%
client.test("get filtered city", function() {
  client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
GET http://localhost:3000/search/filter/:text?text=Cupcake
Content-Type: application/json

> {%
client.test("get filtered text = cupcake", function() {
  client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
GET http://localhost:3000/search/filter/:text?text=Piano
Content-Type: application/json

> {%
client.test("get filtered text = piano", function() {
  client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
GET http://localhost:3000/search/filter/:text?text=Piano&city=Bern
Content-Type: application/json

> {%
client.test("get filtered text = piano", function() {
  client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
GET http://localhost:3000/search/filter/:text?category=Entertainment&subtype=comedy
Content-Type: application/json

> {%
client.test("get filtered category = entertainment", function() {
  client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
