###
# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

//geht nur mit neuer addresse
POST http://localhost:3000/signup
Content-Type: application/json

{
  "firstname": "Example",
  "lastname": "Miller",
  "email": "rayshawn.abdalla@iiron.us",
  "pwhash": "47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=",
  "zip": 3031,
  "street": "Herestreet",
  "housenumber": 11,
  "city": "Bern",
  "isVerified": false
}

> {%
client.test("Sign up normal ", function() {
  client.assert(response.status === 201, "Response status is 201");
  client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###

POST http://localhost:3000/signup
Content-Type: application/json

{
  "firstname": "Example",
  "lastname": "Miller",
  "email": "will123459@gmail.com",
  "pwhash": -1425372064,
  "zip": 3031,
  "street": "Herestreet",
  "housenumber": 11,
  "city": "Bern",
  "isVerified": false
}

> {%
client.test("Sign up with same email address  ", function() {
  client.assert(response.status === 400, "Response status is 400");
  client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
POST http://localhost:3000/signup/sendMailAgain
Content-Type: application/json

{
  "email": "will123459@gmail.com"

}

> {%
client.test("Send mail again normal  ", function() {
  client.assert(response.status === 200, "Response status is 200");
  client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}


###
POST http://localhost:3000/signup/sendMailAgain
Content-Type: application/json

{
  "email": "will123459dd@gmail.com"

}

> {%
client.test("Send mail again error, no user found ", function() {
  client.assert(response.status === 404, "Response status is 404");
  client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
//TODO confirmation token tests fehlen... aber zuerst bug fixen
GET http://localhost:3000/signup/confirmation/eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2lsbGlhbiIsInN1cm5hbWUiOiJDQSIsImVtYWlsIjoiZ2lsbGlhbi5jYXRob21hc0BnbXguY2giLCJpYXQiOjE1NzMzODI4NzcsImV4cCI6MTU3MzQ2OTI3NywiYXVkIjoiZ2lsbGlhbi5jYXRob21hc0BnbXguY2giLCJpc3MiOiJFdmVudGRvbyIsInN1YiI6ImdpbGxpYW4uY2F0aG9tYXNAZ214LmNoIn0.VCPikJPvi4am5k3unwoKISBnE--u3m0cpzlskDt7rRYLwXGbA8TGZscepvcm4iQIGAIzROtLAFDow6SswzVfzQ
Content-Type: application/json

{
  "email": "gillian.cathomas@gmx.ch"


}


> {%
client.test("verify normal  ", function() {
  client.assert(response.status === 200, "Response status is 200");
  client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
GET http://localhost:3000/signup/confirmation/:token
Content-Type: application/json

{
  "email": "gillian.cathomas@gmx.ch",
  "url": "localhost:4200/start/signup/confirmation/deyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQUMiLCJzdXJuYW1lIjoiQ0EiLCJlbWFpbCI6ImdpbGxpYW4uY2F0aG9tYXNAZ214LmNoIiwiaWF0IjoxNTczMzA1OTg0LCJleHAiOjE1NzMzOTIzODQsImF1ZCI6ImdpbGxpYW4uY2F0aG9tYXNAZ214LmNoIiwiaXNzIjoiRXZlbnRkb28iLCJzdWIiOiJnaWxsaWFuLmNhdGhvbWFzQGdteC5jaCJ9.TVorfgkxC2S736-qXaUSJWI1IqcSE2QVP9eG6EvLldl17SYtwMN7fzI642d_QxNXOPjb4c0aQ58BVRyqtIIgnQ"

}


> {%
client.test("verify token invalid  ", function() {
  client.assert(response.status === 406 , "Response status is 406");
  client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

### //TODO test tomorrow
GET http://localhost:3000/signup/confirmation/:token
Content-Type: application/json

{
  "email": "gillian.cathomas@gmx.ch",
  "url": "localhost:4200/start/signup/confirmation/eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQUMiLCJzdXJuYW1lIjoiQ0EiLCJlbWFpbCI6ImdpbGxpYW4uY2F0aG9tYXNAZ214LmNoIiwiaWF0IjoxNTczMzA1OTg0LCJleHAiOjE1NzMzOTIzODQsImF1ZCI6ImdpbGxpYW4uY2F0aG9tYXNAZ214LmNoIiwiaXNzIjoiRXZlbnRkb28iLCJzdWIiOiJnaWxsaWFuLmNhdGhvbWFzQGdteC5jaCJ9.TVorfgkxC2S736-qXaUSJWI1IqcSE2QVP9eG6EvLldl17SYtwMN7fzI642d_QxNXOPjb4c0aQ58BVRyqtIIgnQ"

}


> {%
client.test("verify token expired  ", function() {
  client.assert(response.status === 401 , "Response status is 401");
  client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
