### Login welches funktioniert
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "kiai.lenard@iiron.us",
  "pwhash": -1425372064
}
> {%
client.test("Login works", function() {
  client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

### Login welches nicht funktioniert weil nicht verified
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "chelsea.giovonni@iiron.us",
  "pwhash": -1425372064
}
> {%
client.test("Login works not because not verified", function() {
  client.assert(response.status === 406, "Response status is 406");
    client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}
###### funktioniert nicht weil passwort falsch
POST http://localhost:3000/login
Content-Type: application/json

{
"email": "nalan.draper@iiron.us",
"pwhash": -1425372965
}

> {%
client.test("Login does not work, wrong password ", function() {
  client.assert(response.status === 404, "Response status is 404");
  client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###

GET http://localhost:3000/login/forgotPassword
Content-Type: application/json

{
  "email": "samarth.kalden@iiron.us"
}

> {%
client.test("Send Mail for Passwort reset ", function() {
  client.assert(response.status === 201, "Response status is 201");
  client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
GET http://localhost:3000/login/forgotPassword
Content-Type: application/json

{
  "email": "will1234579@gmail.com"
}

> {%
client.test("Send Password reset, invalid email ", function() {
  client.assert(response.status === 400, "Response status is 400");
  client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
GET http://localhost:3000/login/resetPassword/:token
Content-Type: application/json

{
  "url": "http://localhost:4200/start/login/resetPassword/eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW1hIiwic3VybmFtZSI6ImJNRE0iLCJlbWFpbCI6InNhbWFydGgua2FsZGVuQGlpcm9uLnVzIiwiaWF0IjoxNTcyODE0MTEzLCJleHAiOjE1NzI4MjEzMTMsImF1ZCI6InNhbWFydGgua2FsZGVuQGlpcm9uLnVzIiwiaXNzIjoiRXZlbnRkb28iLCJzdWIiOiJzYW1hcnRoLmthbGRlbkBpaXJvbi51cyJ9.1tAkMLCw1zTX73nQRFd34t_DP_OSdTNJpzocrG9JRgIqKYk29r4TCltMHB2KEkp_smU0DLDZEm1aJbqbJY8d4Qc4eNZLd9F59oTnB5bRfgsrncBxsRQA6u0GOSHfdRAUC28aCvY-NhesZ_RJmGIMAPRinE-HO_XYas0I21RMyvs",
  "newPwHash":-1395788608
}

> {%
client.test("Forgot Password, verify", function() {
  client.assert(response.status === 200, "Response status is 200");
  client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

### //TODO fix bug
GET http://localhost:3000/login/resetPassword/:token
Content-Type: application/json

{
  "url": "http://localhost:4200/start/login/resetPassword/eyJjhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW1hIiwic3VybmFtZSI6ImJNRE0iLCJlbWFpbCI6InNhbWFydGgua2FsZGVuQGlpcm9uLnVzIiwiaWF0IjoxNTcyODE0MTEzLCJleHAiOjE1NzI4MjEzMTMsImF1ZCI6InNhbWFydGgua2FsZGVuQGlpcm9uLnVzIiwiaXNzIjoiRXZlbnRkb28iLCJzdWIiOiJzYW1hcnRoLmthbGRlbkBpaXJvbi51cyJ9.1tAkMLCw1zTX73nQRFd34t_DP_OSdTNJpzocrG9JRgIqKYk29r4TCltMHB2KEkp_smU0DLDZEm1aJbqbJY8d4Qc4eNZLd9F59oTnB5bRfgsrncBxsRQA6u0GOSHfdRAUC28aCvY-NhesZ_RJmGIMAPRinE-HO_XYas0I21RMyvs",
  "newPwHash":-1395788608
}

> {%
client.test("Forgot Password, verify not working because token was changed", function() {
  client.assert(response.status === 406, "Response status is 200");
  client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
