### Send POST request with json body
POST http://localhost:3000/signup
Content-Type: application/json

{
  "firstname": "Example",
  "lastname": "Miller",
  "email": "yarel.aras@iiron.us",
  "pwhash": -1425372064,
  "zip": 3031,
  "street": "Herestreet",
  "housenumber": 11,
  "city": "Bern"
}




###
