### Send POST request with json body
POST http://localhost:3000/signup
Content-Type: application/json

{
  "firstname": "Example",
  "lastname": "Miller",
  "email": "will123459@gmail.com",
  "pwhash": -1425372064,
  "zip": 3031,
  "street": "Herestreet",
  "housenumber": 11,
  "city": "Bern"
}

###
//GEHT anscheinend.....
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "will123459@gmail.com",
  "pwhash": -1425372064
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "karrar.ichigo@thtt.us",
  "pwhash": -1425372064
}

###
