###Funktionierendes erstellen von Eventservices
GET http://localhost:3000/search
Content-Type: application/json

> {%
client.test("get all Services", function() {
  client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
GET http://localhost:3000/search/filter/:category/:city?category=Gastronomy&city=Bern
Content-Type: application/json

> {%
client.test("get filtered gastronomy and city services", function() {
  client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
GET http://localhost:3000/search/filter/:category/:city/:price?category=Gastronomy&price=124

Content-Type: application/json

> {%
client.test("get filtered gastronomy and price services", function() {
  client.assert(response.status === 200, "Response status is 200");
    client.assert(response.body.isEmpty !== -1, "Response is not empty")
});
%}

###
